name = "open-collective-auth"
main = "src/index.ts"
compatibility_date = "2022-11-28"

[vars]
DISCORD_REDIRECT_URL = "https://link.tako-bot.com/discord/redirect"
OPEN_COLLECTIVE_REDIRECT_URL = "https://link.tako-bot.com/open-collective/redirect"
OPEN_COLLECTIVE_SLUG = "tako"

# Necessary secrets:
# - OPEN_COLLECTIVE_CLIENT_ID
# - OPEN_COLLECTIVE_CLIENT_SECRET
# - DISCORD_CLIENT_ID
# - DISCORD_CLIENT_SECRET
# - DISCORD_WEBHOOK_URL
# - SECRET_KEY
